name: CI-GPU-template

on:
  workflow_call:

jobs:
  gpu-tests:
    runs-on: [self-hosted, x64, gpu, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install latest stable 3.x jina version
        run: |
          JINA_VERSION=$(curl -L -s "https://pypi.org/pypi/jina/json" \
            |  jq  -r '.releases | keys | .[]
              #| select(contains("dev") | not) TODO uncomment this once jina3 is released
              | select(startswith("3."))' \
            | sort -V | tail -1)
          pip install jina==${JINA_VERSION}
      - name: Python requirements
        run: pip install -r gpu_requirements.txt -r tests/requirements.txt
      - name: Run GPU tests
        run: python -m pytest -s -v -m "gpu"
